import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import data from "../../questions.json";
import { useDeadPlantWrapper } from "../context/deadplantcontext";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function Home() {
  const { deadplants, addDeadPlant, resetDeadPlants } = useDeadPlantWrapper();
  const [message, setMessage] = useState("");

  function getRndInteger(min, max) {
    return Math.floor(Math.random() * (max - min)) + min;
  }

  if (deadplants > 0) {
    useEffect(() => {
      setMessage(data[1].message[getRndInteger(0, data[1].message.length)]);
    });
  } else {
    useEffect(() => {
      setMessage("");
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Why My Plant Die</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>WHAT WRONG WITH YOUR PLANT</h1>

        <div className={styles.card}>
          <h2>PLANTS KILLED</h2>
          <p>
            {message} {deadplants} plants killed
          </p>
        </div>
        <div className={styles.grid}>
          <div className={styles.card} onClick={resetDeadPlants}>
            <h1>RESET</h1>
          </div>

          {data.map((ele) => {
            if (ele.type == "counter") {
              return (
                <div onClick={addDeadPlant} className={styles.card}>
                  <h1>HELP MY PLANT DEAD!</h1>
                </div>
              );
            }
          })}
        </div>
        <Link href="/plantdoctor">
          <a>
            <div className={styles.card}>
              <h1>HELP MY PLANT DYING</h1>
            </div>
          </a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by DEAD PLANTS
        </a>
      </footer>
    </div>
  );
}
