import Head from "next/head";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function PlantDoctor() {
  const [questionState, setQuestionState] = useState("");

  const handleNo = (e) => {
    e.preventDefault();
    setQuestionState("no");
  };
  const handleYes = (e) => {
    e.preventDefault();
    setQuestionState("yes");
  };
  const handleReset = (e) => {
    e.preventDefault();
    setQuestionState("");
  };

  useEffect(() => {
    setQuestionState("");
  }, []);

  console.log(questionState);

  return (
    <div className="">
      <Head>
        <title>Plant Doctor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="">WHAT WRONG WITH YOUR PLANT</h1>

        <div>
          {questionState === "" ? (
            <div>
              <h1>Did you water?</h1>
              <button className="" onClick={handleYes}>
                Yes
              </button>
              <button onClick={handleNo}>No</button>
            </div>
          ) : null}
        </div>
        <div>
          {questionState === "yes" ? (
            <>
              <h1>Overwatered</h1>
              <button className="" onClick={handleReset}>
                Diagnose another Plant
              </button>
            </>
          ) : null}
        </div>
        <div>
          {questionState === "no" ? (
            <>
              <h1>Underwatered</h1>
              <button className="" onClick={handleReset}>
                Diagnose another Plant
              </button>
            </>
          ) : null}
        </div>
        <Link href="/">
          <a>
            <button className="">back to main page</button>
          </a>
        </Link>
      </main>

      <footer className="">Powered by DEAD PLANTS</footer>
    </div>
  );
}
