import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import data from "../../questions.json";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function PlantDoctor() {
  const [questionState, setQuestionState] = useState("");

  const handleNo = (e) => {
    e.preventDefault();
    setQuestionState("no");
  };
  const handleYes = (e) => {
    e.preventDefault();
    setQuestionState("yes");
  };
  const handleReset = (e) => {
    e.preventDefault();
    setQuestionState("");
  };

  useEffect(() => {
    setQuestionState("");
  }, []);

  console.log(questionState);

  return (
    <div className={styles.container}>
      <Head>
        <title>Plant Doctor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>WHAT WRONG WITH YOUR PLANT</h1>

        <div>
          {questionState === "" ? (
            <div>
              <h1>Did you water?</h1>
              <div className={styles.card} onClick={handleYes}>
                Yes
              </div>
              <div className={styles.card} onClick={handleNo}>
                No
              </div>
            </div>
          ) : null}
        </div>
        <div>
          {questionState === "yes" ? (
            <>
              <h1>Overwatered</h1>
              <div className={styles.card} onClick={handleReset}>
                Diagnose another Plant
              </div>
            </>
          ) : null}
        </div>
        <div>
          {questionState === "no" ? (
            <>
              <h1>Underwatered</h1>
              <div className={styles.card} onClick={handleReset}>
                Diagnose another Plant
              </div>
            </>
          ) : null}
        </div>
        <Link href="/">
          <a>
            <div className={styles.card}>back to main page</div>
          </a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by DEAD PLANTS
        </a>
      </footer>
    </div>
  );
}
